### ISSUE TITLE
Move to Netlify

### ISSUE THREAD

**Issue by Jamesking56** [Jamesking56/jamesking.dev#50]
Migrate the site to Netlify. Migrating offers these benefits:

1. Netlify supports automatic deployment from Git and PR deploy previews.
2. We can (eventually) remove the jamesking56.uk cPanel account
3. We can instantly test any Dependabot updates as a PR deploy preview will be generated by Netlify
4. We can store Netlify config as code
5. Netlify can handle the contact form, meaning spam prevention will also be provided (goodbye `contact.php` and recaptcha!)
6. Netlify allows us to inject scripts outside of the code, meaning we could inject Smartlook and other analytics without needing commits in this repo.
7. Allows me to completely delete my Codeship account

## Todo

- [x] Create Netlify Site and link to this repo.
- [x] Add Netlify config to this repo.
- [x] Convert contact form to use Netlify forms instead, removing `contact.php` completely.
- [x] Move analytics scripts from code to Cloudflare (Google Tag Manager)
- [x] Delete Codeship account
- [x] Add custom domain `jamesking56.uk` to Netlify
- [x] Update DNS for `jamesking56.uk`
- [x] Delete Recaptcha site key
- [x] Recycle Trustpilot API key
