### ISSUE TITLE
jamesking.dev

### ISSUE THREAD

**Issue by Jamesking56** [Jamesking56/jamesking.dev#79]
🎉 After a 2 year wait, I've finally managed to acquire `jamesking.dev` 🎉 

Of course, we need some edits to this repo to get it setup and redirect `jamesking56.uk` to the new domain.

- [x] Change GitHub Repo name #83
- [x] Setup new Google Tag and add Google Analytics #81 
- [x] Add redirects for `jamesking56.uk` and `jamesking56.co.uk` #82
